apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-m18e
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/design-empire-tenant/my-app/devfile-sample-m18e@sha256:0fa81c74acc748125e736a06b899ce1b6f8dab6caf258c53b6478fdb838d67a9
        name: my-nodejs
        resources: {}
status: {}
